apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zoo
  namespace: kafka
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
